/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ImageSelect {}
  interface ImageSelectAttributes extends StencilHTMLAttributes {}

  interface ImageTextSelect {
    'alt': string;
    'src': string;
  }
  interface ImageTextSelectAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'src'?: string;
  }

  interface ImageText {}
  interface ImageTextAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'ImageSelect': Components.ImageSelect;
    'ImageTextSelect': Components.ImageTextSelect;
    'ImageText': Components.ImageText;
  }

  interface StencilIntrinsicElements {
    'image-select': Components.ImageSelectAttributes;
    'image-text-select': Components.ImageTextSelectAttributes;
    'image-text': Components.ImageTextAttributes;
  }


  interface HTMLImageSelectElement extends Components.ImageSelect, HTMLStencilElement {}
  var HTMLImageSelectElement: {
    prototype: HTMLImageSelectElement;
    new (): HTMLImageSelectElement;
  };

  interface HTMLImageTextSelectElement extends Components.ImageTextSelect, HTMLStencilElement {}
  var HTMLImageTextSelectElement: {
    prototype: HTMLImageTextSelectElement;
    new (): HTMLImageTextSelectElement;
  };

  interface HTMLImageTextElement extends Components.ImageText, HTMLStencilElement {}
  var HTMLImageTextElement: {
    prototype: HTMLImageTextElement;
    new (): HTMLImageTextElement;
  };

  interface HTMLElementTagNameMap {
    'image-select': HTMLImageSelectElement
    'image-text-select': HTMLImageTextSelectElement
    'image-text': HTMLImageTextElement
  }

  interface ElementTagNameMap {
    'image-select': HTMLImageSelectElement;
    'image-text-select': HTMLImageTextSelectElement;
    'image-text': HTMLImageTextElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
